### ISSUE TITLE
Design doc review #1 

### ISSUE THREAD

**Issue by aracpyon** [Serendipitydeus/PXelation#1]
Hi Jonathan! Great job on design doc so far. Here are my comments:

- mention what app you are cloning on the wiki page. 

**MVP**
- [x] add update and delete to your 3rd MVP. You should be able to edit your photos and delete the photos 
- [x] Move comments and likes from your 4th MVP to bonus. Comments and likes are separate tables and `Home Feed` and `User profile` pages features have to come first. 

**Schema**

- Follows

- [x] To be more semantic, change `user_id` to `photographer_id`

- Comments

- [x] add `body`

- User profiles

- [x] remove `User Profile tables`. Instead make a joins table(`gallery_photos`) between galleries and photos with foreign keys of `gallery_id` and `photo_id`

- Categories

- [x] remove `photo_id` column
- [x] Make a joins table(`photo_categories`) between categories and photos with foreign keys of photo_id and category_id. Photo can have many categories and each category can have many photos.

**Comment by jonathan-calixto** [comment]
I've completed all the requested changes, please let me know if there are any additional changes required.
