### ISSUE TITLE
Design Doc review #2 - state

### ISSUE THREAD

**Issue by aracpyon** [Serendipitydeus/PXelation#2]
- [x] all the slices will be camel-cased ex. `liker_id` =>  likerId`
- [x] change `Naturalized state` to `Sample State`
- [x] remove `liker_ids` from `users` and add it to `photos`. On users, you may add `liked_photo_ids` instead
- [x] change ` category` to `category_ids: [ ]` because photo can have many categories and you need to create a joins table of `photo_categories`
 - [x] add `body` to comments

**Comment by jonathan-calixto** [comment]
Changes have been made!
